# For more information: https://laravel.com/docs/sail
version: '3.9'
services:
    portal:
        container_name: creoserver-portal.dev
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            # - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - creoserver-network
    portal-frontend:
        container_name: creoserver-portal-frontend.dev
        user: ${WWWUSER}:${WWWGROUP}
        restart: unless-stopped
        image: node:14
        volumes:
            - ./:/app
        working_dir: /app
        command:
            - "npm run watch"
        tty: true
        networks:
            - creoserver-network



networks:
    creoserver-network:
        external: true

