# For more information: https://laravel.com/docs/sail
version: '3.9'
services:
    nginx:
        container_name: creoserver-portal-nginx
        image: nginx:alpine
        ports:
            - "8020:80"
        volumes:
            - ./:/var/www
            - ./nginx/ssl:/ssl:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        restart: unless-stopped
        depends_on:
            -   portal
        networks:
            - creoserver-network
    portal:
        container_name: creoserver-portal
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        image: creoserver-portal
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - creoserver-network
    php-installation:
        container_name: portal-php-installation
        image: creoserver-portal
        depends_on:
            - portal
        working_dir: /app
        volumes:
            - ./:/app
        command: composer install --no-interaction --optimize-autoloader --no-dev
    js-installation:
        container_name: portal-js-installation
        image: node:14
        depends_on:
            -   portal
        working_dir: /app
        tty: true
        volumes:
            -   ./:/app
        command: sh -c "npm install && npm run prod"
        user: 1000:1000


networks:
    creoserver-network:
        name: creoserver-network
        external: true
#        attachable: true


